version: "3.8"

services:
  datagatevpn:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${TARGETARCH}
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    container_name: datagatevpn_tgbot_${DEPLOY_ENV}_container
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./appsettings.Development.json:/app/appsettings.Development.json
      - ./datagatetgbot.pem:/app/datagatetgbot.pem
      - ./datagatetgbot.key:/app/datagatetgbot.key
      - ./bot.gif:/app/bot.gif
      - /etc/openvpn/easy-rsa:/etc/openvpn/easy-rsa
      - /etc/openvpn/clients:/etc/openvpn/clients
      - /etc/openvpn/crl.pem:/etc/openvpn/crl.pem
      - /var/log/openvpn-status.log:/var/log/openvpn-status.log