#!/bin/bash

cat > appsettings.json << 'EOF'
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "ConnectionStrings": {
    "DefaultConnection": "Host=*;Port=5432;Database=*;Username=*;Password=*"
  },
  "BotConfiguration": {
    "BotToken": "*",
    "BotWebhookUrl": "https://08ca-213-133-91-43.ngrok-free.app/bot",
    "SecretToken": ""
  },
  "OpenVpn": {
    "ServerIp": "0.0.0.0",
    "EasyRsaPath": "/etc/openvpn/easy-rsa",
    "OutputDir": "/etc/openvpn/clients",
    "TlsAuthKey": "/etc/openvpn/easy-rsa/pki/ta.key"
  },
  "AllowedHosts": "*"
}
EOF

cat > appsettings.Development.json << 'EOF'
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "ConnectionStrings": {
    "DefaultConnection": "Host=*;Port=5432;Database=*;Username=*;Password=*"
  },
  "BotConfiguration": {
    "BotToken": "*",
    "BotWebhookUrl": "https://08ca-213-133-91-43.ngrok-free.app/bot",
    "SecretToken": ""
  },
  "OpenVpn": {
    "ServerIp": "0.0.0.0",
    "EasyRsaPath": "/etc/openvpn/easy-rsa",
    "OutputDir": "/etc/openvpn/clients",
    "TlsAuthKey": "/etc/openvpn/easy-rsa/pki/ta.key"
  },
  "AllowedHosts": "*"
}
EOF

git add appsettings.json
git add appsettings.json appsettings.Development.json