name: Build and Deploy DataGateVPNBot develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: Build and Deploy on Raspberry Pi
    env:
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use existing configuration files
        run: |
          cp /home/rackot/configs/appsettings.json ./DataGateVPNBot/appsettings.json
          cp /home/rackot/configs/appsettings.Development.json ./DataGateVPNBot/appsettings.Development.json
          
          cp /home/rackot/certs/datagatetgbot.pem ./DataGateVPNBot/datagatetgbot.pem
          cp /home/rackot/certs/datagatetgbot.key ./DataGateVPNBot/datagatetgbot.key
          
          cp /home/rackot/Photo/bot.gif ./bot.gif

      - name: Verify files
        run: |
          echo "Verifying required files..."
          for file in DataGateVPNBot/appsettings.json DataGateVPNBot/appsettings.Development.json DataGateVPNBot/datagatetgbot.pem DataGateVPNBot/datagatetgbot.key bot.gif; do
            if [ -s ./$file ]; then
              echo "$file is present and not empty.";
            else
              echo "$file is missing or empty!";
              exit 1;
            fi
          done

      - name: Build Docker image
        run: |
          docker build -t datagatevpn-develop -f DataGateVPNBot/Dockerfile-develop .

      - name: Deploy Docker container
        run: |
          docker stop datagatevpn_develop_container || true
          docker rm datagatevpn_develop_container || true
          docker run -d --name datagatevpn_develop_container \
          -p 88:88 \
          -e ASPNETCORE_ENVIRONMENT=Development \
          -v $PWD/appsettings.json:/app/appsettings.json \
          -v $PWD/appsettings.Development.json:/app/appsettings.Development.json \
          -v $PWD/datagatetgbot.pem:/app/datagatetgbot.pem \
          -v $PWD/datagatetgbot.key:/app/datagatetgbot.key \
          -v $PWD/bot.gif:/app/bot.gif \
          -v /etc/openvpn/easy-rsa:/etc/openvpn/easy-rsa \
          -v /etc/openvpn/clients:/etc/openvpn/clients \
          -v /etc/openvpn/crl.pem:/etc/openvpn/crl.pem \
          -v /var/log/openvpn-status.log:/var/log/openvpn-status.log \
          datagatevpn-develop