name: Build and Deploy DataGateVPNBot (Develop)

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: Build and Deploy on Raspberry Pi (Develop)
    env:
      DEPLOY_ENV: develop
      ENV_FILE: .env.develop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load Environment Variables
        run: cat $ENV_FILE >> $GITHUB_ENV

      - name: Use existing configuration files
        run: |
          cp /home/rackot/configs/appsettings.json ./appsettings.json
          cp /home/rackot/configs/appsettings.Development.json ./appsettings.Development.json
          cp /home/rackot/certs/datagatetgbot.pem ./datagatetgbot.pem
          cp /home/rackot/certs/datagatetgbot.key ./datagatetgbot.key
          cp /home/rackot/Photo/bot.gif ./bot.gif

      - name: Verify files
        run: |
          echo "Verifying required files..."
          for file in appsettings.json appsettings.Development.json datagatetgbot.pem datagatetgbot.key bot.gif; do
            if [ -s ./$file ]; then
              echo "$file is present and not empty.";
            else
              echo "$file is missing or empty!";
              exit 1;
            fi
          done

      - name: Stop and Remove Existing Container
        run: |
          docker compose --env-file $ENV_FILE down || true

      - name: Build and Deploy with Docker Compose
        run: |
          docker compose --env-file $ENV_FILE up --build -d