name: Build and Deploy DataGateVPNBot develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create appsettings.json
      run: |
        echo "${{ secrets.APPSETTINGS_DEV_JSON }}" > ./appsettings.json

    - name: Create appsettings.Development.json
      run: |
        echo "${{ secrets.APPSETTINGS_DEV_JSON }}" > ./appsettings.Development.json

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile-develop
        push: false
        tags: datagatevpn:develop

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.RPI_HOST }} >> ~/.ssh/known_hosts

    - name: Save Docker image as tar
      run: |
        docker save datagatevpn:develop -o datagatevpn_develop.tar

    - name: Deploy application to Raspberry Pi
      run: |
        scp datagatevpn_develop.tar pi@${{ secrets.RPI_HOST }}:/home/pi/
        ssh pi@${{ secrets.RPI_HOST }} << EOF
          docker load < /home/pi/datagatevpn_develop.tar
          docker stop datagatevpn || true
          docker rm datagatevpn || true
          docker-compose -f /path/to/docker-compose.override.yml up -d
        EOF
