name: Build and Deploy DataGateVPNBot develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: Build and Deploy on Raspberry Pi
    env:
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create appsettings.json
        run: |
          echo "${{ secrets.APPSETTINGS_DEV_JSON }}" > ./appsettings.json

      - name: Create appsettings.Development.json
        run: |
          echo "${{ secrets.APPSETTINGS_DEV_JSON }}" > ./appsettings.Development.json

      - name: Build Docker image
        run: |
          docker build -t datagatevpn-develop -f Dockerfile-develop .

      - name: Deploy Docker container
        run: |
          docker stop datagatevpn_develop_container || true
          docker rm datagatevpn_develop_container || true
          docker run -d --name datagatevpn_develop_container -p 5501:88 \
            -e ASPNETCORE_ENVIRONMENT=Development \
            -v $PWD/appsettings.json:/app/appsettings.json \
            -v $PWD/appsettings.Development.json:/app/appsettings.Development.json \
            datagatevpn-develop
