name: Build and Deploy DataGateVPNBot develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: datagatevpn:develop
        platforms: linux/arm/v7

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.RPI_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy application to Raspberry Pi
      run: |
        ssh pi@${{ secrets.RPI_HOST }} << EOF
          docker load < datagatevpn:develop.tar
          docker stop datagatevpn || true
          docker rm datagatevpn || true
          docker-compose -f /path/to/docker-compose.override.yml up -d
        EOF
