name: Build and Deploy DataGateVPNBot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./DataGateVPNBotV1.csproj

    - name: Build application
      run: dotnet publish ./DataGateVPNBotV1.csproj -c Release -r linux-arm64 --self-contained true -o ./publish

      - name: Deploy Docker container
        run: |
          docker stop datagatevpn_main_container || true
          docker rm datagatevpn_main_container || true
          docker run -d --name datagatevpn_main_container \
          -p 8443:8443 \
          -e ASPNETCORE_ENVIRONMENT=Production \
          -v $PWD/appsettings.json:/app/appsettings.json \
          -v $PWD/appsettings.Development.json:/app/appsettings.Development.json \
          -v $PWD/datagatetgbot.pem:/app/datagatetgbot.pem \
          -v $PWD/datagatetgbot.key:/app/datagatetgbot.key \
          -v $PWD/bot.gif:/app/bot.gif \
          -v /etc/openvpn/easy-rsa:/etc/openvpn/easy-rsa \
          -v /etc/openvpn/clients:/etc/openvpn/clients \
          -v /etc/openvpn/crl.pem:/etc/openvpn/crl.pem \
          datagatevpn-main
